config/routes.rb
Rails.application.routes.draw do

  
  resources :grade_levels
  resources :homerooms
  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories
    resources :referrals, only: [:index]
    resources :students, only: [:index]
    resources :homerooms
    resources :grade_levels
  end

  resources :categories
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'students#index'

  post 'students/upload', to: 'students#upload'
  
  resources :students do
    resources :referrals
  end
  
  resources :users do
    resources :referrals
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  # searchkick word_start: [:first_name, :last_name, :homeroom, :grade_level, :student_id_number, :full_name]

  def full_name
    "#{first_name} #{last_name}"
  end

  # def search_data
  # {
  #   full_name: full_name,
  #   first_name: first_name,
  #   last_name: last_name,
  #   homeroom: homeroom,
  #   grade_level: grade_level,
  #   student_id_number: student_id_number
  # }
  # end
  
  belongs_to :homeroom, required: false, dependent: :destroy
  belongs_to :grade_level
  has_many :users
  has_many :referrals, dependent: :destroy
  
  accepts_nested_attributes_for :homeroom
  accepts_nested_attributes_for :grade_level

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'csv'

  before_action :set_student, only: [:show, :edit, :update, :destroy]
  # before_action :set_grade_level, only: [:edit, :update, :destroy]
  # before_action :set_homeroom, only: [:edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.json
      format.js
      format.html
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @referrals = @student.referrals
    @referral = Referral.new
  end

  def upload
    CSV.foreach(params[:leads].path, headers: true) do |lead|
        grade_level = GradeLevel.find_or_create_by(grade: lead[3])
        homeroom = Homeroom.find_or_create_by(room_number: lead[4], grade_level_id: grade_level.id)
        student = Student.create(first_name: lead[0], last_name: lead[1], student_id_number: lead[2], grade_level_id: grade_level.id, homeroom_id: homeroom.id)
    end
    redirect_to students_path
  end

  # GET /students/new
  def new
    @student = Student.new
    @homeroom = @student.build_homeroom
    @grade_level = @student.build_grade_level
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    
    @student = Student.new(student_params)
    @student.homeroom = Homeroom.find_or_create_by(params[:room_number])
    @student.grade_level = GradeLevel.find_or_create_by(params[:grade])
    # @homeroom = @student.build_homeroom(homeroom_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # def set_grade_level
    #   @grade_level = GradeLevel.find(params[:grade])
    # end

    # def set_homeroom
    #   @homeroom = Homeroom.find(params[:homeroom_id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit!
      #(:first_name, :last_name, :student_id_number, :grade_level, homeroom_attributes: [:homeroom_id, :room_number])
    end
    
    # def homeroom_params
    #   params.permit(:room_number)
    # end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for @student do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :student_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :student_last_name %>
  </div>

  <div class="field">
    <%= form.label :student_id_number %>
    <%= form.number_field :student_id_number, id: :student_student_id_number %>
  </div>

  <div class="field">
    <%= form.simple_fields_for :grade_level do |hr| %>
      <%= hr.label :grade %>
      <%= hr.text_field :grade %>
    <% end %>
  </div>

  <div class="field">
    <%= form.simple_fields_for :homeroom do |hr| %>
      <%= hr.label :room_number %>
      <%= hr.text_field :room_number %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<header>
  <h1>Students</h1>
  <ul class="actions">
			<li><%= link_to 'New Student', new_student_path, class: 'new' %></li>
      <li><%= form_tag students_upload_path, multipart: true do %></li>
      <li><%= file_field_tag :leads %></li>
      <li><%= submit_tag "Import Students" %></li>
      <% end %>
		</ul>
</header>

<table class='search-table table search'>
  <thead>
    <tr>
      <th style="display:none">Full Name</th>
      <th style="display:none">Homeroom</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Student ID Number</th>
      <th>Grade level</th>
      <th>Homeroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td style="display:none"><%= student.full_name.downcase%></td>
        <td style="display:none"><%= student.homeroom.room_number.to_s.downcase%></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.student_id_number %></td>
        <td><%= student.grade_level.grade %></td>
        <td><%= student.homeroom.room_number %></td>
        <td><%= link_to 'Add Referral', new_student_referral_path(student) %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<header>
  <h1>Student Overview</h1>
  <%= link_to 'Add Referral', new_student_referral_path(@student) %> |
  <%= link_to 'Edit', edit_student_path(@student) %> |
  <%= link_to 'Back', students_path %> |
</header>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Student id number:</strong>
  <%= @student.student_id_number %>
</p>

<p>
  <strong>Grade level:</strong>
  <%= @student.grade_level.grade %>
</p>

<p>
  <strong>Homeroom:</strong>
  <%= @student.homeroom.room_number %>
</p>

<h2>Total Referrals: <%= @student.referrals.count %></h2>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Referral</th>
      <th>Referral Type</th>
      <th>Occurance Date</th>
      <th>Created Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral|  %>
      <tr>
        <td><%= referral.user.name %></td>
        <td><%= link_to referral.note, student_referral_path(@student, referral) %></td>
        <td><%= referral.category.name %></td>
        <td><%= time_format(referral.occurance_date) %></td>
        <td><%= time_format(referral.created_at) %></td>
      </tr>
    <% end %>
  </tbody>

</table>