config/routes.rb
Rails.application.routes.draw do

  
  resources :grade_levels
  resources :homerooms
  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories
    resources :referrals, only: [:index]
    resources :students, only: [:index]
    resources :homerooms
    resources :grade_levels
  end

  resources :categories
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'students#index'

  post 'students/upload', to: 'students#upload'
  
  resources :students do
    resources :referrals
  end
  
  resources :users do
    resources :referrals
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index
    @users = User.all
    @categories = Category.all
    @referrals = Referral.all
    @homerooms = Homeroom.all
    @grade_levels = GradeLevel.all
  end

  private

	def authorize_admin!
		authenticate_user!

		unless current_user.admin?
			flash[:alert] = "You do not have permission to perform this action"
			redirect_to students_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def time_format(referral_date)
		referral_date.strftime("%A, %b %e %Y at %l:%M %p ")
  end
  
end

app/views/admin/application/index.html.erb
<h1>Admin Panel</h1>

<ul>
  <li>
    <%= link_to admin_users_path do %>
      Users: <%= @users.count %>
    <% end %>
  </li>

  <li>
    <%= link_to admin_categories_path do %>
      Categories: <%= @categories.count %>
    <% end %>
  </li>

  <li>
    <%= link_to admin_referrals_path do %>
      Referrals: <%= @referrals.count %>
    <% end %>
  </li>

  <li>
    <%= link_to admin_homerooms_path do %>
      Homerooms: <%= @homerooms.count %>
    <% end %>
  </li>

   <li>
    <%= link_to admin_grade_levels_path do %>
      Grade Levels: <%= @grade_levels.count %>
    <% end %>
  </li>

</ul>