config/routes.rb
Rails.application.routes.draw do

  
  resources :grade_levels
  resources :homerooms
  namespace :admin do
    root 'application#index'
    resources :users, only: [:index]
    resources :categories
    resources :referrals, only: [:index]
    resources :students, only: [:index]
    resources :homerooms
    resources :grade_levels
  end

  resources :categories
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'students#index'

  post 'students/upload', to: 'students#upload'
  
  resources :students do
    resources :referrals
  end
  
  resources :users do
    resources :referrals
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :referrals

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
	before_action :authorize_owner, except: [:index]
	before_action :set_category, only: [:edit, :update, :destroy, :show]

	def index
		@users = User.all
		@categories = Category.order(:name)
	end

	def show
		@categories = Category.all
		@referrals = @category.referrals
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category Created!"
			redirect_to admin_categories_path
		else
			flash.now[:alert] = "Category Not Created!"
			render :new
		end
	end

	def edit
	end

	def update
		if @category.update(category_params)
			flash[:notice] = "Category Updated!"
			redirect_to admin_categories_path
		else
			flash.now[:alert] = "Category Not Updated!"
			render :edit
		end
	end

	def destroy
		@category.destroy
		flash[:alert] = "Category has been deleted."
		redirect_to admin_categories_path
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def set_category
		@category = Category.find(params[:id])
	end

	def authorize_owner
		authenticate_user!
		unless current_user.admin?
			flash[:alert] = "You do not have permission to perform this action"
			redirect_to students_path
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, category]) do |f| %>
  <%= f.input :name %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<header>
	<h1>Categories</h1>
		<ul class="actions">
			<li><%= link_to "New Category", new_admin_category_path, class: 'new' %></li>
		</ul>
</header>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Referrals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category|  %>
      <tr>
        <td><%= link_to category.name, admin_category_path(category) %></td>
        <td><%= category.referrals.count %></td>
        <td>
          <%= link_to "Edit", edit_admin_category_path(category) %> | <%= link_to "Delete", admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<header>
  <h1><%= @category.name %> Referrals </h1>
</header>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Homeroom</th>
      <th>Referral</th>
      <th>Date Occured</th>
      <th>Date Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referrals.each do |referral|  %>
      <tr>
        <td><%= link_to referral.student.first_name + " " + referral.student.last_name, student_path(referral.student) %></td>
        <td><%= link_to referral.student.homeroom.room_number, admin_homeroom_path(referral.student.homeroom) %></td>
        <td><%= link_to referral.note, student_referral_path(referral.student, referral) %></td>
        <td><%= time_format(referral.occurance_date) %></td>
        <td><%= time_format(referral.created_at) %></td>

      </tr>
    <% end %>
  </tbody>

</table>